services:
  sonarr:
    build: ./sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    networks:
      - appnet

  idp:
    build: ..
    container_name: idp
    ports:
      - "8080:8080"
    networks:
      - appnet

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - sonarr
      - idp
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
